const products = [
  {
    _id: "64e78abcf001a1a5d0010001",
    name: "Wireless Bluetooth Headphones",
    mainImage: "/images/airpods_main.jpg",
    images: [
      "/images/airpods_1.jpg",
      "/images/airpods_2.jpg",
      "/images/airpods_3.jpg",
    ],
    description:
      "High-quality wireless headphones with rich sound and seamless connectivity.",
    price: 8999,
    countInStock: 10,
    specifications: [
      { label: "Brand", value: "Sony" },
      { label: "Model Number", value: "WH-CH710N" },
      { label: "Dimensions", value: "7.6 x 2.1 x 9.6 inches" },
      { label: "Weight", value: "223 grams" },
      { label: "Material", value: "Plastic and Metal" },
      { label: "Color", value: "Black" },
      { label: "Origin", value: "Japan" },
    ],
  },
  {
    _id: "64e78abcf001a1a5d0010002",
    name: "Smart Fitness Watch",
    mainImage: "/images/watch_main.jpg",
    images: [
      "/images/watch_1.jpg",
      "/images/watch_2.jpg",
      "/images/watch_3.jpg",
    ],
    description:
      "Track your activity and heart rate with this stylish smart watch.",
    price: 4999,
    countInStock: 0,
    specifications: [
      { label: "Brand", value: "FitPro" },
      { label: "Model Number", value: "FP-W202" },
      { label: "Dimensions", value: "4.4 x 3.6 x 1.1 cm" },
      { label: "Weight", value: "45 grams" },
      { label: "Material", value: "Silicone and Glass" },
      { label: "Color", value: "Blue" },
      { label: "Origin", value: "China" },
    ],
  },
  {
    _id: "64e78abcf001a1a5d0010003",
    name: "Portable Bluetooth Speaker",
    mainImage: "/images/speaker_main.jpg",
    images: [
      "/images/speaker_1.jpg",
      "/images/speaker_2.jpg",
      "/images/speaker_3.jpg",
    ],
    description: "Compact speaker with deep bass and 10 hours of playtime.",
    price: 2999,
    countInStock: 20,
    specifications: [
      { label: "Brand", value: "JBL" },
      { label: "Model Number", value: "GO3" },
      { label: "Dimensions", value: "8.6 x 6.9 x 4 cm" },
      { label: "Weight", value: "209 grams" },
      { label: "Material", value: "Fabric and Plastic" },
      { label: "Color", value: "Red" },
      { label: "Origin", value: "USA" },
    ],
  },
  {
    _id: "64e78abcf001a1a5d0010004",
    name: "Noise Cancelling Earbuds",
    mainImage: "/images/earbuds_main.jpg",
    images: [
      "/images/earbuds_1.jpg",
      "/images/earbuds_2.jpg",
      "/images/earbuds_3.jpg",
    ],
    description:
      "Enjoy distraction-free audio with premium noise cancellation.",
    price: 6499,
    countInStock: 12,
    specifications: [
      { label: "Brand", value: "Samsung" },
      { label: "Model Number", value: "Galaxy Buds 2" },
      { label: "Dimensions", value: "2 x 2 x 1 inches" },
      { label: "Weight", value: "42 grams" },
      { label: "Material", value: "Plastic" },
      { label: "Color", value: "White" },
      { label: "Origin", value: "South Korea" },
    ],
  },
  {
    _id: "64e78abcf001a1a5d0010005",
    name: "USB-C Charging Cable",
    mainImage: "/images/usb-c_main.jpg",
    images: [
      "/images/usb-c_1.jpg",
      "/images/usb-c_2.jpg",
      "/images/usb-c_3.jpg",
    ],
    description: "Fast charging USB-C cable for all your devices.",
    price: 499,
    countInStock: 50,
    specifications: [
      { label: "Brand", value: "Anker" },
      { label: "Model Number", value: "A8852" },
      { label: "Dimensions", value: "1 meter" },
      { label: "Weight", value: "30 grams" },
      { label: "Material", value: "Nylon Braided" },
      { label: "Color", value: "Black" },
      { label: "Origin", value: "Vietnam" },
    ],
  },
  {
    _id: "64e78abcf001a1a5d0010006",
    name: "Wireless Gaming Mouse",
    mainImage: "/images/mouse_main.jpg",
    images: [
      "/images/mouse_1.jpg",
      "/images/mouse_2.jpg",
      "/images/mouse_3.jpg",
    ],
    description: "Ergonomic and lag-free mouse designed for gamers.",
    price: 1999,
    countInStock: 18,
    specifications: [
      { label: "Brand", value: "Logitech" },
      { label: "Model Number", value: "G305" },
      { label: "Dimensions", value: "11.6 x 6.2 x 3.8 cm" },
      { label: "Weight", value: "99 grams" },
      { label: "Material", value: "Plastic" },
      { label: "Color", value: "Grey" },
      { label: "Origin", value: "Switzerland" },
    ],
  },
  {
    _id: "64e78abcf001a1a5d0010007",
    name: "Mechanical Gaming Keyboard",
    mainImage: "/images/keyboard_main.jpg",
    images: [
      "/images/keyboard_1.jpg",
      "/images/keyboard_2.jpg",
      "/images/keyboard_3.jpg",
    ],
    description: "RGB backlit mechanical keyboard with tactile switches.",
    price: 4599,
    countInStock: 8,
    specifications: [
      { label: "Brand", value: "Redragon" },
      { label: "Model Number", value: "K552" },
      { label: "Dimensions", value: "35.4 x 12.3 x 3.7 cm" },
      { label: "Weight", value: "800 grams" },
      { label: "Material", value: "Metal and ABS" },
      { label: "Color", value: "RGB Black" },
      { label: "Origin", value: "China" },
    ],
  },
  {
    _id: "64e78abcf001a1a5d0010008",
    name: "1080p HD Web Camera",
    mainImage: "/images/webcam_main.jpg",
    images: [
      "/images/webcam_1.jpg",
      "/images/webcam_2.jpg",
      "/images/webcam_3.jpg",
    ],
    description:
      "Full HD webcam with built-in mic for video calls and streaming.",
    price: 1499,
    countInStock: 25,
    specifications: [
      { label: "Brand", value: "Logitech" },
      { label: "Model Number", value: "C270" },
      { label: "Dimensions", value: "7.2 x 2.9 x 6.2 cm" },
      { label: "Weight", value: "75 grams" },
      { label: "Material", value: "Plastic" },
      { label: "Color", value: "Black" },
      { label: "Origin", value: "Mexico" },
    ],
  },
];

export default products;
